plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/trader/rsa-app/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
VITE_BACKEND_URL = "https://rsa-backend-production-7b95.up.railway.app"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]